#!/bin/bash
#set -x
set -u
export PATH=.:$PATH
command="$@"

assert_output_is()
{
  expected="$1"
  out=$($command)
  [ "$out" = "$expected" ] || { printf "Failure\nExpected: ${expected}\nGot     : %s\n" "$out"; exit 1; }
}

assert_output_is "Hello, world"
printf "Success!\n"
