#!/bin/bash
set -x
export PATH=.:$PATH
out=$(echo "Dan" | $*)
[ "$out" = "Hello, Dan" ] || { printf "Failure\nExpected: Hello, Dan\nGot     : %s\n" "$out"; exit 1; }
out=$(echo "Jiro" | $*)
[ "$out" = "Hello, Jiro" ] || { printf "Failure\nExpected: Hello, Jiro\nGot     : %s\n" "$out"; exit 1; }
printf "Success!\n"
