#!/bin/bash
set -x
export PATH=.:$PATH
out=$($* --name "Dan")
[ "$out" = "Hello, Dan" ] || { printf "Failure\nExpected: Hello, Dan\nGot     : %s\n" "$out"; exit 1; }
out=$($* --name "Jiro")
[ "$out" = "Hello, Jiro" ] || { printf "Failure\nExpected: Hello, Jiro\nGot     : %s\n" "$out"; exit 1; }
printf "Success!\n"
