#!/bin/bash
#set -u
set -x

GO_VERSION="$1"
shift

[[ -s "$HOME/.gvm/scripts/gvm" ]] && source "$HOME/.gvm/scripts/gvm"

gvm use "$GO_VERSION"
PKGSET_NAME=$(pwd | sed 's~/~_~g')

setup_pkgset()
{
	gvm pkgset create "$PKGSET_NAME"
	gvm pkgset use "$PKGSET_NAME"
	setup_dot_gopkg
}

setup_dot_gopkg()
{
	[ -e .gopkg ] || mkdir .gopkg
	[ -e .gopkg/solution.go ] || ln -s `readlink -e solution.go` .gopkg/solution.go
	if [ -e scratch.go ]; then
		[ -e .gopkg/scratch.go ] || ln -s `readlink -e scratch.go` .gopkg/scratch.go
	fi
	pushd .gopkg
	go get -d .
	popd
}

gvm pkgset use "$PKGSET_NAME" || { setup_pkgset && gvm pkgset use "$PKGSET_NAME"; }
setup_dot_gopkg

$*
